import type { WorldCup, Era } from './types';

export const WORLD_CUPS: WorldCup[] = [
  {
    year: 1930, host: 'Uruguay', winner: 'Uruguay', runnerUp: 'Argentina',
    score: '4–2', mvp: 'José Nasazzi', mvpCountry: 'Uruguay',
    mvpType: 'Star Player',
    fact: 'The inaugural World Cup — only 13 teams made the long journey to Montevideo by boat.',
    era: 'Origins',
  },
  {
    year: 1934, host: 'Italy', winner: 'Italy', runnerUp: 'Czechoslovakia',
    score: '2–1 (aet)', mvp: 'Giuseppe Meazza', mvpCountry: 'Italy',
    mvpType: 'Star Player',
    fact: 'The first World Cup with qualification rounds. Italy triumphed on home soil under intense national pressure.',
    era: 'Origins',
  },
  {
    year: 1938, host: 'France', winner: 'Italy', runnerUp: 'Hungary',
    score: '4–2', mvp: 'Leônidas', mvpCountry: 'Brazil',
    mvpType: 'Star Player',
    fact: 'Italy became the first team to defend the title. The last World Cup before a 12-year hiatus due to WWII.',
    era: 'Origins',
  },
  {
    year: 1950, host: 'Brazil', winner: 'Uruguay', runnerUp: 'Brazil',
    score: '2–1', mvp: 'Zizinho', mvpCountry: 'Brazil',
    mvpType: 'Star Player',
    fact: 'The "Maracanazo" — Uruguay stunned 200,000 fans in Rio. Brazil only needed a draw but lost 2–1.',
    era: 'Post-War',
  },
  {
    year: 1954, host: 'Switzerland', winner: 'West Germany', runnerUp: 'Hungary',
    score: '3–2', mvp: 'Ferenc Puskás', mvpCountry: 'Hungary',
    mvpType: 'Star Player',
    fact: 'The "Miracle of Bern" — Hungary had been unbeaten for four years before West Germany pulled off the impossible.',
    era: 'Post-War',
  },
  {
    year: 1958, host: 'Sweden', winner: 'Brazil', runnerUp: 'Sweden',
    score: '5–2', mvp: 'Pelé', mvpCountry: 'Brazil',
    mvpType: 'Star Player',
    fact: 'A 17-year-old Pelé scored twice in the final, announcing himself to the world on the biggest stage.',
    era: 'Post-War',
  },
  {
    year: 1962, host: 'Chile', winner: 'Brazil', runnerUp: 'Czechoslovakia',
    score: '3–1', mvp: 'Garrincha', mvpCountry: 'Brazil',
    mvpType: 'Star Player',
    fact: 'Garrincha carried Brazil after Pelé was injured in the second group match. Back-to-back titles secured.',
    era: 'Post-War',
  },
  {
    year: 1966, host: 'England', winner: 'England', runnerUp: 'West Germany',
    score: '4–2 (aet)', mvp: 'Bobby Charlton', mvpCountry: 'England',
    mvpType: 'Star Player',
    fact: '"They think it\'s all over — it is now!" England\'s controversial third goal still sparks debate decades later.',
    era: 'Post-War',
  },
  {
    year: 1970, host: 'Mexico', winner: 'Brazil', runnerUp: 'Italy',
    score: '4–1', mvp: 'Pelé', mvpCountry: 'Brazil',
    mvpType: 'Star Player',
    fact: 'Widely considered the greatest team ever assembled. Brazil won the Jules Rimet trophy permanently with their third title.',
    era: 'Golden Age',
  },
  {
    year: 1974, host: 'West Germany', winner: 'West Germany', runnerUp: 'Netherlands',
    score: '2–1', mvp: 'Johan Cruyff', mvpCountry: 'Netherlands',
    mvpType: 'Star Player',
    fact: '"Total Football" — the Netherlands revolutionized the game forever but fell in the final to the hosts.',
    era: 'Golden Age',
  },
  {
    year: 1978, host: 'Argentina', winner: 'Argentina', runnerUp: 'Netherlands',
    score: '3–1 (aet)', mvp: 'Mario Kempes', mvpCountry: 'Argentina',
    mvpType: 'Star Player',
    fact: 'Ticker tape celebrations filled Buenos Aires. Argentina\'s first title came amid political controversy at home.',
    era: 'Golden Age',
  },
  {
    year: 1982, host: 'Spain', winner: 'Italy', runnerUp: 'West Germany',
    score: '3–1', mvp: 'Paolo Rossi', mvpCountry: 'Italy',
    mvpType: 'Golden Ball',
    fact: 'Paolo Rossi returned from a two-year match-fixing ban to score six goals and become a national hero.',
    era: 'Golden Age',
  },
  {
    year: 1986, host: 'Mexico', winner: 'Argentina', runnerUp: 'West Germany',
    score: '3–2', mvp: 'Diego Maradona', mvpCountry: 'Argentina',
    mvpType: 'Golden Ball',
    fact: 'Maradona\'s "Hand of God" and "Goal of the Century" — both in the same quarterfinal against England.',
    era: 'Golden Age',
  },
  {
    year: 1990, host: 'Italy', winner: 'West Germany', runnerUp: 'Argentina',
    score: '1–0', mvp: 'Salvatore Schillaci', mvpCountry: 'Italy',
    mvpType: 'Golden Ball',
    fact: 'The most defensive World Cup in history. A single Andreas Brehme penalty decided a dour final.',
    era: 'Golden Age',
  },
  {
    year: 1994, host: 'United States', winner: 'Brazil', runnerUp: 'Italy',
    score: '0–0 (3–2 pen)', mvp: 'Romário', mvpCountry: 'Brazil',
    mvpType: 'Golden Ball',
    fact: 'The first World Cup in the USA. Roberto Baggio\'s infamous missed penalty haunted Italy in the shootout.',
    era: 'Modern Era',
  },
  {
    year: 1998, host: 'France', winner: 'France', runnerUp: 'Brazil',
    score: '3–0', mvp: 'Ronaldo', mvpCountry: 'Brazil',
    mvpType: 'Golden Ball',
    fact: 'Zinedine Zidane scored twice as France won on home soil. The mystery of Ronaldo\'s pre-final seizure endures.',
    era: 'Modern Era',
  },
  {
    year: 2002, host: 'South Korea / Japan', winner: 'Brazil', runnerUp: 'Germany',
    score: '2–0', mvp: 'Oliver Kahn', mvpCountry: 'Germany',
    mvpType: 'Golden Ball',
    fact: 'The first Asian World Cup and the only time a goalkeeper has won the Golden Ball. Ronaldo scored both final goals.',
    era: 'Modern Era',
  },
  {
    year: 2006, host: 'Germany', winner: 'Italy', runnerUp: 'France',
    score: '1–1 (5–3 pen)', mvp: 'Zinedine Zidane', mvpCountry: 'France',
    mvpType: 'Golden Ball',
    fact: 'Zidane\'s headbutt on Materazzi in his farewell match — from genius to infamy in 110 minutes.',
    era: 'Modern Era',
  },
  {
    year: 2010, host: 'South Africa', winner: 'Spain', runnerUp: 'Netherlands',
    score: '1–0 (aet)', mvp: 'Diego Forlán', mvpCountry: 'Uruguay',
    mvpType: 'Golden Ball',
    fact: 'The first African World Cup. Spain\'s tiki-taka philosophy conquered the world. The vuvuzela became the soundtrack.',
    era: 'Modern Era',
  },
  {
    year: 2014, host: 'Brazil', winner: 'Germany', runnerUp: 'Argentina',
    score: '1–0 (aet)', mvp: 'Lionel Messi', mvpCountry: 'Argentina',
    mvpType: 'Golden Ball',
    fact: 'Germany humiliated Brazil 7–1 in the semi-final — the most shocking scoreline in World Cup history.',
    era: 'Modern Era',
  },
  {
    year: 2018, host: 'Russia', winner: 'France', runnerUp: 'Croatia',
    score: '4–2', mvp: 'Luka Modrić', mvpCountry: 'Croatia',
    mvpType: 'Golden Ball',
    fact: 'VAR used for the first time in World Cup history. Croatia\'s fairy-tale run to the final captivated the world.',
    era: 'Modern Era',
  },
  {
    year: 2022, host: 'Qatar', winner: 'Argentina', runnerUp: 'France',
    score: '3–3 (4–2 pen)', mvp: 'Lionel Messi', mvpCountry: 'Argentina',
    mvpType: 'Golden Ball',
    fact: 'The first winter World Cup. Messi\'s crowning glory — widely considered the greatest final ever played.',
    era: 'Modern Era',
  },
];

export const COUNTRY_COLORS: Record<string, [string, string]> = {
  Uruguay:        ['#4A8FE7', '#f0f0f0'],
  Italy:          ['#0066B2', '#004494'],
  'West Germany': ['#1a1a1a', '#DD0000'],
  Germany:        ['#1a1a1a', '#DD0000'],
  Brazil:         ['#009739', '#FEDD00'],
  England:        ['#CF081F', '#f0f0f0'],
  Argentina:      ['#6CACE4', '#f0f0f0'],
  France:         ['#002654', '#ED2939'],
  Spain:          ['#C60B1E', '#FFC400'],
};

export const ERAS: Era[] = [
  { id: 'Origins',    label: 'THE ORIGINS',      range: '1930–1938' },
  { id: 'Post-War',   label: 'POST-WAR REVIVAL',  range: '1950–1966' },
  { id: 'Golden Age', label: 'THE GOLDEN AGE',    range: '1970–1990' },
  { id: 'Modern Era', label: 'THE MODERN ERA',    range: '1994–2022' },
];
